parameters:
    php_orchestra_media.doctrine_listener.move_uploaded_file.class: PHPOrchestra\Media\EventListener\MoveUploadedFileListener
services:
    php_orchestra_media.doctrine_listener.move_uploaded_file:
        class: %php_orchestra_media.doctrine_listener.move_uploaded_file.class%
        arguments:
            - %php_orchestra_media.upload_dir%
            - @php_orchestra_media.thumbnail_manager
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: postUpdate }
