parameters:
    php_orchestra_media.manager.image_resizer.class: PHPOrchestra\Media\Manager\ImageResizerManager

services:
    php_orchestra_media.manager.image_resizer:
        class: %php_orchestra_media.manager.image_resizer.class%
        arguments:
            - %php_orchestra_media.upload_dir%
            - %php_orchestra_media.thumbnail.configuration%