parameters:
    php_orchestra_media.subscriber.generate_image.class: PHPOrchestra\Media\EventSubscriber\GenerateImageSubscriber

services:
    php_orchestra_media.subscriber.generate_image:
        class: %php_orchestra_media.subscriber.generate_image.class%
        arguments:
            - %php_orchestra_media.upload_dir%
            - %php_orchestra_media.thumbnail.configuration%
        tags:
             - { name: kernel.event_subscriber }
