parameters:
    php_orchestra_media.twig.display_media.extension.class: PHPOrchestra\MediaBundle\Twig\DisplayMediaExtension

services:
    php_orchestra_media.twig.display_media.extension:
        class: %php_orchestra_media.twig.display_media.extension.class%
        arguments:
            - @php_orchestra_media.display_media_manager
            - @php_orchestra_media.repository.media
        tags:
            - { name: twig.extension }
