language: php

cache:
  directories:
    - ~/.composer/cache
    - ~/composer

php:
  - 5.5

sudo: false

before_install:
  - phpenv config-add .travis.php.ini
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - export COMPOSER_ROOT_VERSION=1.1.x-dev
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 46e87a82e243bfa43aa0891996c1659323c9bf73923e21c539842719fa64206d 

after_script:
  - ./bin/test-reporter
