language: php

cache:
  directories:
    - ~/.composer/cache

php:
  - 5.4

sudo: false

before_install:
  - phpenv config-add .travis.php.ini
  - composer self-update

install:
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=46e87a82e243bfa43aa0891996c1659323c9bf73923e21c539842719fa64206d ./bin/test-reporter
