OpenOrchestra\ModelBundle\Document\Area:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueAreaId: ~
    properties:
        areaId:
            - NotBlank: ~
        subAreas:
            - Valid: ~
