OpenOrchestra\ModelBundle\Document\ContentType:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueContentTypeId: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueFieldIdContentType: ~
    properties:
        deleted:
            - Type:
                type: bool
        contentTypeId:
            - OpenOrchestra\ModelBundle\Validator\Constraints\IdAuthorizedCharacter: ~
        names:
            - Valid: ~
        fields:
            - Valid: ~
