OpenOrchestra\ModelBundle\Document\ContentType:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueContentTypeId: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueFieldIdContentType: ~
    properties:
        deleted:
            - Type:
                type: bool
        contentTypeId:
            - Regex:
                pattern: '/^[a-zA-Z0-9_][a-zA-Z0-9_\-:]*$/D'
                message: 'open_orchestra_model_validators.field.special_character'
        name:
            - Valid: ~
        fields:
            - Valid: ~
