OpenOrchestra\ModelBundle\Document\Content:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\CheckPublishingDate: ~
    properties:
        name:
            - NotBlank: ~
        siteId:
            - NotBlank: ~
        contentType:
            - NotBlank: ~
        language:
            - NotBlank: ~
        deleted:
            - Type:
                type: bool
        attributes:
            - Valid: ~
