OpenOrchestra\ModelBundle\Document\FieldType:
    properties:
        searchable:
            - Type:
                type: bool
        translatable:
            - Type:
                type: bool
        listable:
            - Type:
                type: bool
        fieldId:
            - Regex:
                pattern: '/^[a-zA-Z0-9_][a-zA-Z0-9_\-:]*$/D'
                message: 'open_orchestra_model_validators.field.special_character'
        labels:
            - Valid: ~
        options:
            - Valid: ~
