OpenOrchestra\ModelBundle\Document\FieldType:
    properties:
        searchable:
            - Type:
                type: bool
        translatable:
            - Type:
                type: bool
        listable:
            - Type:
                type: bool
        fieldId:
            - OpenOrchestra\ModelBundle\Validator\Constraints\IdAuthorizedCharacter: ~
        labels:
            - Valid: ~
        options:
            - Valid: ~
