OpenOrchestra\ModelBundle\Document\Node:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\PreventProhibitedStatusChange: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\CheckRoutePattern: ~
    properties:
        nodeType:
            - NotBlank: ~
        siteId:
            - NotBlank: ~
        parentId:
            - NotBlank: ~
        name:
            - NotBlank: ~
        boLabel:
            - NotBlank: { groups: [page] }
        language:
            - NotBlank: ~
        routePattern:
            - NotBlank: ~
        deleted:
            - Type:
                type: bool
        inMenu:
            - Type:
                type: bool
        themeSiteDefault:
            - Type:
                type: bool
        inFooter:
            - Type:
                type: bool
        order:
            - Type:
                type: integer
        rootArea:
            - Valid: ~
