OpenOrchestra\ModelBundle\Document\Role:
    properties:
        name:
            - NotBlank: ~
        fromStatus:
            - Valid: ~
        toStatus:
            - Valid: ~
        descriptions:
            - Valid: ~
