OpenOrchestra\ModelBundle\Document\Site:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueMainAlias: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueSiteId: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\CheckMainAliasPresence: ~
    properties:
        siteId:
            - NotBlank: ~
        name:
            - NotBlank: ~
        deleted:
            - Type:
                type: bool
        theme:
            - Valid: ~
        aliases:
            - Valid: ~
