OpenOrchestra\ModelBundle\Document\Site:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueSiteId: ~
    properties:
        siteId:
            - NotBlank: ~
        name:
            - NotBlank: ~
        metaAuthor:
            - NotBlank: ~
        deleted:
            - Type:
                type: bool
        aliases:
            - Valid: ~
            - Count:
                min: 1
