OpenOrchestra\ModelBundle\Document\SiteAlias:
    properties:
        domain:
            - NotBlank: ~
        language:
            - NotBlank: ~
        main:
            - Type:
                type: bool
