OpenOrchestra\ModelBundle\Document\Status:
    properties:
        name:
            - NotBlank: ~
        displayColor:
            - NotBlank: ~
        labels:
            - Valid: ~
        publishedState:
            - Type:
                type: bool
        initialState :
            - Type:
                type: bool
