OpenOrchestra\ModelBundle\Document\Template:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueAreaId: ~
    properties:
        name:
            - NotBlank: ~
        language:
            - NotBlank: ~
        boDirection:
            - NotBlank: ~
        deleted:
            - Type:
                type: bool
        areas:
            - Valid: ~
