parameters:
    php_orchestra_indexation.index_manager.class: PHPOrchestra\IndexationBundle\IndexationStrategy\IndexerManager
    php_orchestra_indexation.indexer_manager.class: PHPOrchestra\IndexationBundle\IndexationStrategy\IndexerManager
    php_orchestra_indexation.solr.strategy.class: PHPOrchestra\IndexationBundle\IndexationStrategy\Strategies\SolrStrategy
    php_orchestra_indexation.search_manager.class: PHPOrchestra\IndexationBundle\SearchStrategy\SearchManager
    php_orchestra_indexation.search.solr.strategy.class: PHPOrchestra\IndexationBundle\SearchStrategy\Strategies\SolrSearchStrategy
    phporchestra_indexation.indexsolr.class: PHPOrchestra\IndexationBundle\IndexCommand\SolrIndexCommand
    php_orchestra_indexation.solr_converter_manager.class: PHPOrchestra\IndexationBundle\SolrConverter\ConverterManager
    php_orchestra_indexation.solr_converter.node.strategy.class: PHPOrchestra\IndexationBundle\SolrConverter\Strategies\NodeConverterStrategy
    php_orchestra_indexation.solr_converter.content.strategy.class: PHPOrchestra\IndexationBundle\SolrConverter\Strategies\ContentConverterStrategy

services:
    phporchestra_indexation.index_manager:
        class: %php_orchestra_indexation.index_manager.class%
        arguments: [@router, @mandango, @solarium.client]
    php_orchestra_indexation.indexer_manager:
        class: %php_orchestra_indexation.indexer_manager.class%
    php_orchestra_indexation.search_manager:
        class: %php_orchestra_indexation.search_manager.class%
    php_orchestra_indexation.solr_converter_manager:
        class: %php_orchestra_indexation.solr_converter_manager.class%

    php_orchestra_indexation.indexer.solr.strategy:
        class: %php_orchestra_indexation.solr.strategy.class%
        arguments:
            - %php_orchestra_indexation.type%
            - @phporchestra_indexation.indexsolr
            - @doctrine_mongodb.odm.document_manager
            - %php_orchestra_model.document.list_index.class%
            - @php_orchestra_model.repository.list_index
        tags:
            - { name: php_orchestra_indexation.indexer.strategy }
    php_orchestra_indexation.search.solr.strategy:
        class: %php_orchestra_indexation.search.solr.strategy.class%
        arguments:
            - %php_orchestra_indexation.type%
            - @solarium.client
        tags:
            - { name: php_orchestra_indexation.search.strategy }
    php_orchestra_indexation.solr_converter.node.strategy:
        class: %php_orchestra_indexation.solr_converter.node.strategy.class%
        arguments:
            - @router
        tags:
            - { name: php_orchestra_indexation.solr_converter.strategy }
    php_orchestra_indexation.solr_converter.content.strategy:
        class: %php_orchestra_indexation.solr_converter.content.strategy.class%
        arguments:
            - @router
            - @php_orchestra_model.repository.node
        tags:
            - { name: php_orchestra_indexation.solr_converter.strategy }

    # IndexCommand service
    phporchestra_indexation.indexsolr:
        class: %phporchestra_indexation.indexsolr.class%
        arguments:
            - @php_orchestra_model.repository.field_index
            - @solarium.client
            - @php_orchestra_indexation.solr_converter_manager
