parameters:
    php_orchestra_model.display_media_manager.class: PHPOrchestra\ModelBundle\DisplayMedia\DisplayMediaManager
    php_orchestra_model.display_media.image.class: PHPOrchestra\ModelBundle\DisplayMedia\Strategies\ImageStrategy
    php_orchestra_model.display_media.pdf.class: PHPOrchestra\ModelBundle\DisplayMedia\Strategies\PdfStrategy
    php_orchestra_model.display_media.video.class: PHPOrchestra\ModelBundle\DisplayMedia\Strategies\VideoStrategy

services:
    php_orchestra_model.display_media_manager:
        class: %php_orchestra_model.display_media_manager.class%
        arguments:
            - %php_orchestra_base.mediatheque.url%
    php_orchestra_model.display_media.image:
        class: %php_orchestra_model.display_media.image.class%
        tags:
            - { name: php_orchestra_model.display_media.strategy }
    php_orchestra_model.display_media.pdf:
        class: %php_orchestra_model.display_media.pdf.class%
        tags:
            - { name: php_orchestra_model.display_media.strategy }
    php_orchestra_model.display_media.video:
        class: %php_orchestra_model.display_media.video.class%
        tags:
            - { name: php_orchestra_model.display_media.strategy }
