parameters:
    open_orchestra_model.type.orchestra_site.class: OpenOrchestra\ModelBundle\Form\Type\OrchestraSiteType
    open_orchestra_model.type.orchestra_role.class: OpenOrchestra\ModelBundle\Form\Type\OrchestraRoleType
    open_orchestra_model.type.orchestra_status.class: OpenOrchestra\ModelBundle\Form\Type\OrchestraStatusType
    open_orchestra_model.type.orchestra_theme.class: OpenOrchestra\ModelBundle\Form\Type\OrchestraThemeType

services:
    open_orchestra_model.type.orchestra_site:
        class: %open_orchestra_model.type.orchestra_site.class%
        arguments:
            - %open_orchestra_model.document.site.class%
        tags:
            - { name: form.type, alias: orchestra_site }
    open_orchestra_model.type.orchestra_role:
        class: %open_orchestra_model.type.orchestra_role.class%
        arguments:
            - %open_orchestra_model.document.role.class%
        tags:
            - { name: form.type, alias: orchestra_role }
    open_orchestra_model.type.orchestra_status:
        class: %open_orchestra_model.type.orchestra_status.class%
        arguments:
            - @open_orchestra_model.transformer.embed_status_to_status
            - %open_orchestra_model.document.status.class%
        tags:
            - { name: form.type, alias: orchestra_status }
    open_orchestra_model.type.orchestra_theme:
        class: %open_orchestra_model.type.orchestra_theme.class%
        arguments:
            - %open_orchestra_model.document.theme.class%
        tags:
            - { name: form.type, alias: orchestra_theme }
