parameters:
    php_orchestra_model.type.orchestra_site.class: PHPOrchestra\ModelBundle\Form\Type\OrchestraSiteType
    php_orchestra_model.type.orchestra_role.class: PHPOrchestra\ModelBundle\Form\Type\OrchestraRoleType
    php_orchestra_model.type.orchestra_status.class: PHPOrchestra\ModelBundle\Form\Type\OrchestraStatusType
    php_orchestra_model.type.orchestra_theme.class: PHPOrchestra\ModelBundle\Form\Type\OrchestraThemeType

services:
    php_orchestra_model.type.orchestra_site:
        class: %php_orchestra_model.type.orchestra_site.class%
        arguments:
            - %php_orchestra_model.document.site.class%
        tags:
            - { name: form.type, alias: orchestra_site }
    php_orchestra_model.type.orchestra_role:
        class: %php_orchestra_model.type.orchestra_role.class%
        arguments:
            - %php_orchestra_model.document.role.class%
        tags:
            - { name: form.type, alias: orchestra_role }
    php_orchestra_model.type.orchestra_status:
        class: %php_orchestra_model.type.orchestra_status.class%
        arguments:
            - @php_orchestra_model.transformer.embed_status_to_status
            - %php_orchestra_model.document.status.class%
        tags:
            - { name: form.type, alias: orchestra_status }
    php_orchestra_model.type.orchestra_theme:
        class: %php_orchestra_model.type.orchestra_theme.class%
        arguments:
            - %php_orchestra_model.document.theme.class%
        tags:
            - { name: form.type, alias: orchestra_theme }
