parameters:
    open_orchestra_model.helper.supress_special_character.class: OpenOrchestra\ModelBundle\Helper\SuppressSpecialCharacterHelper
services:
    open_orchestra_model.helper.supress_special_character:
        class: %open_orchestra_model.helper.supress_special_character.class%
