parameters:
    php_orchestra_model.doctrine_listener.generate_node_id.class: PHPOrchestra\ModelBundle\EventListener\GenerateNodeIdListener
    php_orchestra_model.doctrine_listener.generate_template_id.class: PHPOrchestra\ModelBundle\EventListener\GenerateTemplateIdListener
    php_orchestra_model.doctrine_listener.generate_content_id.class: PHPOrchestra\ModelBundle\EventListener\GenerateContentIdListener
    php_orchestra_model.doctrine_listener.initial_status.class: PHPOrchestra\ModelBundle\EventListener\InitialStatusListener
    php_orchestra_model.doctrine_listener.generate_path.class: PHPOrchestra\ModelBundle\EventListener\GeneratePathListener
    php_orchestra_model.doctrine_listener.set_initial_status.class: PHPOrchestra\ModelBundle\EventListener\SetInitialStatusListener
    php_orchestra_model.doctrine_listener.move_uploaded_file.class: PHPOrchestra\ModelBundle\EventListener\MoveUploadedFileListener
    php_orchestra_model.doctrine_listener.save_published_document.class: PHPOrchestra\ModelBundle\EventListener\SavePublishedDocumentListener
    php_orchestra_model.doctrine_listener.transversal_node_creator.class: PHPOrchestra\ModelBundle\EventListener\TransversalNodeCreatorListener
    php_orchestra_model.doctrine_listener.default_theme.class: PHPOrchestra\ModelBundle\EventListener\DefaultThemeListener

services:
    php_orchestra_model.doctrine_listener.initial_status:
        class: %php_orchestra_model.doctrine_listener.initial_status.class%
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
            -  { name: doctrine_mongodb.odm.event_listener, event: postFlush }
    php_orchestra_model.doctrine_listener.set_initial_status:
        class: %php_orchestra_model.doctrine_listener.set_initial_status.class%
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }
    php_orchestra_model.doctrine_listener.generate_path:
        class: %php_orchestra_model.doctrine_listener.generate_path.class%
        arguments:
            - @service_container
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
    php_orchestra_model.doctrine_listener.generate_node_id:
        class: %php_orchestra_model.doctrine_listener.generate_node_id.class%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
    php_orchestra_model.doctrine_listener.generate_template_id:
        class: %php_orchestra_model.doctrine_listener.generate_template_id.class%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
    php_orchestra_model.doctrine_listener.generate_content_id:
        class: %php_orchestra_model.doctrine_listener.generate_content_id.class%
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
    php_orchestra_model.doctrine_listener.move_uploaded_file:
        class: %php_orchestra_model.doctrine_listener.move_uploaded_file.class%
        arguments:
            - %php_orchestra_model.upload_dir%
            - @php_orchestra_model.thumbnail_manager
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }
            - { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
            - { name: doctrine_mongodb.odm.event_listener, event: postPersist }
            - { name: doctrine_mongodb.odm.event_listener, event: postUpdate }
    php_orchestra_model.doctrine_listener.save_published_document:
        class: %php_orchestra_model.doctrine_listener.save_published_document.class%
#        tags:
#            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
    php_orchestra_model.doctrine_listener.transversal_node_creator:
        class: %php_orchestra_model.doctrine_listener.transversal_node_creator.class%
        arguments:
            - @service_container
            - @php_orchestra_model.manager.node
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }
    php_orchestra_model.doctrine_listener.default_theme:
        class: %php_orchestra_model.doctrine_listener.default_theme.class%
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
            -  { name: doctrine_mongodb.odm.event_listener, event: postFlush }
