parameters:
    open_orchestra_model.doctrine_listener.generate_id.class                          : OpenOrchestra\ModelBundle\EventListener\GenerateIdListener
    open_orchestra_model.doctrine_listener.generate_path.class                        : OpenOrchestra\ModelBundle\EventListener\GeneratePathListener
    open_orchestra_model.doctrine_listener.update_non_translatable_content_field.class: OpenOrchestra\ModelBundle\EventListener\UpdateNonTranslatableContentFieldsListener

services:
    open_orchestra_model.doctrine_listener.generate_path:
        class: '%open_orchestra_model.doctrine_listener.generate_path.class%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist }
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
            -  { name: doctrine_mongodb.odm.event_listener, event: postFlush }

    open_orchestra_model.doctrine_listener.generate_id:
        class: '%open_orchestra_model.doctrine_listener.generate_id.class%'
        arguments:
            - '@annotations.reader'
            - '@open_orchestra_model.helper.suppress_special_character'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            - { name: doctrine_mongodb.odm.event_listener, event: prePersist }

    open_orchestra_model.doctrine_listener.update_non_translatable_content_field:
        class: '%open_orchestra_model.doctrine_listener.update_non_translatable_content_field.class%'
        arguments:
            - '%open_orchestra_model.document.content_attribute.class%'
            - '%open_orchestra_model.content.immutable_properties%'
        calls:
            - [setContainer, ['@service_container']]
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate }
