parameters:
    open_orchestra_model.manager.node.class: OpenOrchestra\ModelBundle\Manager\NodeManager

services:
    open_orchestra_model.manager.node:
        class: %open_orchestra_model.manager.node.class%
        arguments:
            - %open_orchestra_model.document.node.class%
        calls:
            - [setContainer, ['@service_container']]

