parameters:
    open_orchestra_model.manager.entity_db_mapper.class: OpenOrchestra\ModelBundle\Manager\EntityDbMapper

services:
    open_orchestra_model.manager.content_for_embed:
        class: '%open_orchestra_model.manager.entity_db_mapper.class%'
        arguments:
            - '@doctrine.odm.mongodb.document_manager'
            - '%open_orchestra_model.document.content.class%'
