parameters:
    open_orchestra_model.manager.versionnable_saver.class: OpenOrchestra\ModelBundle\Manager\VersionableSaver

services:
    open_orchestra_model.manager.versionnable_saver:
        class: %open_orchestra_model.manager.versionnable_saver.class%
        calls:
            - [setContainer, ['@service_container']]
