resolve_target_documents:
    # @deprecated will be removed in 2.0
    OpenOrchestra\ModelInterface\Model\TranslatedValueInterface: OpenOrchestra\ModelBundle\Document\TranslatedValue
    OpenOrchestra\ModelInterface\Model\ReadSiteInterface: OpenOrchestra\ModelBundle\Document\Site
    OpenOrchestra\ModelInterface\Model\EmbedStatusInterface: OpenOrchestra\ModelBundle\Document\EmbedStatus
    # @deprecated will be removed in 2.0
    OpenOrchestra\ModelInterface\Model\EmbedKeywordInterface: OpenOrchestra\ModelBundle\Document\EmbedKeyword
    OpenOrchestra\ModelInterface\Model\KeywordInterface: OpenOrchestra\ModelBundle\Document\Keyword
    OpenOrchestra\ModelInterface\Model\RoleInterface: OpenOrchestra\ModelBundle\Document\Role
    OpenOrchestra\ModelInterface\Model\AreaInterface: OpenOrchestra\ModelBundle\Document\Area
    OpenOrchestra\ModelInterface\Model\BlockInterface: OpenOrchestra\ModelBundle\Document\Block
    OpenOrchestra\ModelInterface\Model\StatusInterface: OpenOrchestra\ModelBundle\Document\Status
    OpenOrchestra\ModelInterface\Model\ThemeInterface: OpenOrchestra\ModelBundle\Document\Theme
    OpenOrchestra\ModelInterface\Model\SiteAliasInterface: OpenOrchestra\ModelBundle\Document\SiteAlias
    OpenOrchestra\ModelInterface\Model\ContentAttributeInterface: OpenOrchestra\ModelBundle\Document\ContentAttribute
    OpenOrchestra\ModelInterface\Model\FieldTypeInterface: OpenOrchestra\ModelBundle\Document\FieldType
    OpenOrchestra\ModelInterface\Model\FieldOptionInterface: OpenOrchestra\ModelBundle\Document\FieldOption
    OpenOrchestra\ModelInterface\Model\HistoryInterface: OpenOrchestra\ModelBundle\Document\History
