resolve_target_documents:
    OpenOrchestra\ModelInterface\Model\ReadSiteInterface                  : OpenOrchestra\ModelBundle\Document\Site
    OpenOrchestra\ModelInterface\Model\EmbedStatusInterface               : OpenOrchestra\ModelBundle\Document\EmbedStatus
    OpenOrchestra\ModelInterface\Model\KeywordInterface                   : OpenOrchestra\ModelBundle\Document\Keyword
    OpenOrchestra\ModelInterface\Model\AreaInterface                      : OpenOrchestra\ModelBundle\Document\Area
    OpenOrchestra\ModelInterface\Model\BlockInterface                     : OpenOrchestra\ModelBundle\Document\Block
    OpenOrchestra\ModelInterface\Model\StatusInterface                    : OpenOrchestra\ModelBundle\Document\Status
    OpenOrchestra\ModelInterface\Model\SiteAliasInterface                 : OpenOrchestra\ModelBundle\Document\SiteAlias
    OpenOrchestra\ModelInterface\Model\ContentAttributeInterface          : OpenOrchestra\ModelBundle\Document\ContentAttribute
    OpenOrchestra\ModelInterface\Model\FieldTypeInterface                 : OpenOrchestra\ModelBundle\Document\FieldType
    OpenOrchestra\ModelInterface\Model\FieldOptionInterface               : OpenOrchestra\ModelBundle\Document\FieldOption
    OpenOrchestra\ModelInterface\Model\HistoryInterface                   : OpenOrchestra\ModelBundle\Document\History
    OpenOrchestra\ModelInterface\Model\WorkflowProfileInterface           : OpenOrchestra\ModelBundle\Document\WorkflowProfile
    OpenOrchestra\ModelInterface\Model\WorkflowProfileCollectionInterface : OpenOrchestra\ModelBundle\Document\WorkflowProfileCollection
    OpenOrchestra\ModelInterface\Model\WorkflowTransitionInterface        : OpenOrchestra\ModelBundle\Document\WorkflowTransition
    OpenOrchestra\ModelInterface\Model\InternalUrlInterface               : OpenOrchestra\ModelBundle\Document\InternalUrl
