parameters:
    open_orchestra_model.saver.versionnable_saver.class: OpenOrchestra\ModelBundle\Saver\VersionableSaver

services:
    open_orchestra_model.saver.versionnable_saver:
        class: %open_orchestra_model.saver.versionnable_saver.class%
        calls:
            - [setContainer, ['@service_container']]
