parameters:
#    php_orchestra_model.example.class: PHPOrchestra\ModelBundle\Example

services:
#    php_orchestra_model.example:
#        class: %php_orchestra_model.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    status_listener:
        class: PHPOrchestra\ModelBundle\EventListener\StatusListener
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: preUpdate, method: preUpdate }
            -  { name: doctrine_mongodb.odm.event_listener, event: postFlush, method: postFlush }
    node_listener:
        class: PHPOrchestra\ModelBundle\EventListener\NodeListener
        tags:
            -  { name: doctrine_mongodb.odm.event_listener, event: prePersist, method: prePersist }

