parameters:
    open_orchestra_model.transformer.embed_status_to_status.class: OpenOrchestra\ModelBundle\Form\DataTransformer\EmbedStatusToStatusTransformer
    open_orchestra_model.transformer.embed_site_to_site.class: OpenOrchestra\ModelBundle\Form\DataTransformer\EmbedSiteToSiteTransformer
    open_orchestra_model.transformer.boolean_to_bdd.class: OpenOrchestra\ModelBundle\Form\DataTransformer\ConditionFromBooleanToMongoTransformer

services:
    open_orchestra_model.transformer.embed_site_to_site:
        class: %open_orchestra_model.transformer.embed_site_to_site.class%
        arguments:
            - @open_orchestra_model.repository.site
    open_orchestra_model.transformer.embed_status_to_status:
        class: %open_orchestra_model.transformer.embed_status_to_status.class%
        arguments:
            - @open_orchestra_model.repository.status
            - %open_orchestra_model.document.embed_status.class%
    open_orchestra_model.transformer.boolean_to_bdd:
        class: %open_orchestra_model.transformer.boolean_to_bdd.class%
        arguments:
            - @open_orchestra_backoffice.manager.keyword_to_reference
            - @open_orchestra_model.repository.keyword
