parameters:
    open_orchestra_model.transformer.embed_status_to_status.class: OpenOrchestra\ModelBundle\Form\DataTransformer\EmbedStatusToStatusTransformer

services:
    open_orchestra_model.transformer.embed_status_to_status:
        class: %open_orchestra_model.transformer.embed_status_to_status.class%
        arguments:
            - @open_orchestra_model.repository.status
            - %open_orchestra_model.document.embed_status.class%
