OpenOrchestra\ModelBundle\Document\Node:
    constraints:
          - OpenOrchestra\ModelBundle\Validator\Constraints\PreventProhibitedStatusChange: ~
#          - OpenOrchestra\ModelBundle\Validator\Constraints\PreventPublishedDocumentSave: ~
          - OpenOrchestra\ModelBundle\Validator\Constraints\CheckAreaPresence: ~
          - OpenOrchestra\ModelBundle\Validator\Constraints\CheckRoutePattern: ~
OpenOrchestra\ModelBundle\Document\Site:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueMainAlias: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueSiteId: ~
