OpenOrchestra\ModelBundle\Document\Node:
    constraints:
          - OpenOrchestra\ModelBundle\Validator\Constraints\PreventProhibitedStatusChange: ~
          - OpenOrchestra\ModelBundle\Validator\Constraints\PreventPublishedDocumentSave: ~
          - OpenOrchestra\ModelBundle\Validator\Constraints\CheckAreaPresence: ~
          - OpenOrchestra\ModelBundle\Validator\Constraints\CheckRoutePattern: ~
OpenOrchestra\ModelBundle\Document\Site:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueMainAlias: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueSiteId: ~
OpenOrchestra\ModelBundle\Document\ContentType:
    constraints:
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueContentTypeId: ~
        - OpenOrchestra\ModelBundle\Validator\Constraints\UniqueFieldIdContentType: ~
    properties:
        contentTypeId:
          - Regex:
              pattern: '/^[a-zA-Z0-9_][a-zA-Z0-9_\-:]*$/D'
              message: 'open_orchestra_model_validators.field.special_character'
        fields:
          - Valid: ~
OpenOrchestra\ModelBundle\Document\FieldType:
    properties:
        fieldId:
          - Regex:
              pattern: '/^[a-zA-Z0-9_][a-zA-Z0-9_\-:]*$/D'
              message: 'open_orchestra_model_validators.field.special_character'
