PHPOrchestra\ModelBundle\Document\Node:
    constraints:
          - PHPOrchestra\ModelBundle\Validator\Constraints\PreventProhibitedStatusChange: ~
#          - PHPOrchestra\ModelBundle\Validator\Constraints\PreventPublishedDocumentSave: ~
          - PHPOrchestra\ModelBundle\Validator\Constraints\CheckAreaPresence: ~
          - PHPOrchestra\ModelBundle\Validator\Constraints\CheckRoutePattern: ~
PHPOrchestra\ModelBundle\Document\Site:
    constraints:
        - PHPOrchestra\ModelBundle\Validator\Constraints\UniqueMainAlias: ~
